# Generated by Django 5.1.1 on 2024-10-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/originals/')),
                ('copy_image', models.ImageField(upload_to='images/copies/')),
                ('original_heatmap', models.ImageField(blank=True, null=True, upload_to='images/heatmaps/')),
                ('copy_heatmap', models.ImageField(blank=True, null=True, upload_to='images/heatmaps/')),
            ],
        ),
    ]
