# Generated by Django 5.1.1 on 2024-10-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.CharField(max_length=255)),
                ('copy_image', models.CharField(max_length=255)),
                ('original_heatmap', models.CharField(max_length=255)),
                ('copy_heatmap', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ImagePair',
        ),
    ]
